stark-bank:
  projectId: 5329009030201344
  bankCode: 20018183
  branch: 0001
  account: 6341320293482496
  name: Stark Bank S.A.
  taxID: 20.018.183/0001-80
  accountType: payment

keys:
  path: C:\\Users\\IGOR\\Downloads\\Invoice-Transactions\\src\\main\\java\\com\\transactions\\Invoice\\main\\config\\keys