keys:
   path: /src/main/java/com/transactions/Invoice/main/config/keys

spring:
  cloud:
    config:
      namespace: default
      enabled: true
      name: Cloud
      profile: dev, cloud, firestone
      label: master
    gcp:
      projectId: deploy-docker-335213
      credentials:
        location: classpath:gcp-key.json
      firestone:
        projectId: deploy-docker-335213
        enabled: false
