name: Build and Push Java Image to Google Cloud Platform
on:
  push:
    branches: [ master ]
jobs:
  build-and-push-gcp:
    name: Build and push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: emanoel01/stark-bank-transactions
      PROJECT_ID: deploy-docker-335213
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ env.PROJECT_ID }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run:  |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker southamerica-east1-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCP)
        env:
          GIT_TAG: v0.1.0
        run:  |-
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG

      - name: Push Docker Image to Artifact Registry (GCP)
        env:
          GIT_TAG: v0.1.0
        run: |-
          docker tag $IMAGE_NAME:latest southamerica-east1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:latest southamerica-east1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push southamerica-east1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
          docker push southamerica-east1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG


        docker tag emanoel01/stark-bank-transactions:v1 southamerica-east1-docker.pkg.dev/deploy-docker-335213/emanoel01/stark-bank-transactions:latest
        docker push southamerica-east1-docker.pkg.dev/deploy-docker-335213/emanoel01/stark-bank-transactions:latest